// <auto-generated />
namespace FrogFoot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ProductCap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductCap));
        
        string IMigrationMetadata.Id
        {
            get { return "201509180709048_ProductCap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
